name = "Plagiarism"
author = "The City of Perth, I guess"
description = """
Go solve this plaque.
What? No, I'm not giving you a key, go find one yourself.
Flag is all lowercase, with underscores for spaces.
"""
category = "osint"
difficulty = "medium"
points = 300
flag = "saint{grease_train}"
