name = "Mysterious File 2"
author = "ning"
description = """
Hmm this seems to be a login system...
Can you find a way to break your way in?

Hint: https://www.youtube.com/watch?v=fTGTnrgjuGA"""
category = "rev"
difficulty = "medium"
points = 300
flag = "saint{d1d_y0u_d1ss4s3mbl3_m3?}"
