name = "weird language"
author = "ning"
description = """
We intercepted some transmissions but they seem to be in some strange language...
What sort of language ends their sentences with '=' anyways??
weirdos.

c2FpbnR7eWVhaF9iYXNlNjRfaXNfc29ydGFfd2VpcmRfbmdsfQ==
"""
category = "crypto"
difficulty = "easy"
points = 60
flag = "saint{yeah_base64_is_sorta_weird_ngl}"
