name = "RSA 1"
author = "ning"
description = """
No key for you this time!

haaaaaaaaa now what will you do?
"""
category = "crypto"
difficulty = "medium"
points = 200
flag = "saint{1t_w4s_l1t3r4lly_4_cub3r00t?}"
